import Foundation

enum DraftActionType: String, Codable, Hashable, Sendable {
    case createTodo = "CREATE_TODO"
    case createNote = "CREATE_NOTE"
    case createList = "CREATE_LIST"
    case updateTodo = "UPDATE_TODO"
    case completeTodo = "COMPLETE_TODO"
    case updateNote = "UPDATE_NOTE"
    case appendToNote = "APPEND_TO_NOTE"
    case updateList = "UPDATE_LIST"
    case addToList = "ADD_TO_LIST"
    case updateListItem = "UPDATE_LIST_ITEM"
    case removeListItem = "REMOVE_LIST_ITEM"
    case updateFolder = "UPDATE_FOLDER"
    case deleteTodo = "DELETE_TODO"
    case deleteNote = "DELETE_NOTE"
    case deleteList = "DELETE_LIST"
    case deleteFolder = "DELETE_FOLDER"
    case createTrip = "CREATE_TRIP"
    case addItineraryItems = "ADD_ITINERARY_ITEMS"
    case updateTrip = "UPDATE_TRIP"
    case deleteTrip = "DELETE_TRIP"
    case updateItineraryItem = "UPDATE_ITINERARY_ITEM"
    case deleteItineraryItem = "DELETE_ITINERARY_ITEM"
    case addExpense = "ADD_EXPENSE"
    case unknown = "UNKNOWN"
}
